In [25]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np
import openpyxl

In [26]:
r=requests.get(url='https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2024-25&SeasonType=Playoffs&StatCategory=PTS').json()

In [27]:
table_headers = r['resultSet']['headers']

In [28]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1628983,1,Shai Gilgeous-Alexander,1610612760,OKC,23,851,233,504,0.462,32,113,0.283,190,217,0.876,23,100,123,150,38,20,60,65,688,661,2.50,0.63
1,1628973,2,Jalen Brunson,1610612752,NYK,18,680,181,393,0.461,48,134,0.358,120,141,0.851,12,50,62,126,8,5,55,59,530,443,2.29,0.14
2,1631114,3,Jalen Williams,1610612760,OKC,23,796,178,396,0.449,35,115,0.304,101,128,0.789,24,103,127,111,32,9,41,50,492,485,2.71,0.78
3,1627783,4,Pascal Siakam,1610612754,IND,23,771,175,341,0.513,35,82,0.427,87,122,0.713,30,116,146,78,28,16,30,66,472,509,2.60,0.93
4,1630169,5,Tyrese Haliburton,1610612754,IND,23,772,146,315,0.463,54,159,0.340,53,64,0.828,7,116,123,197,30,15,53,39,399,531,3.72,0.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,200782,207,P.J. Tucker,1610612752,NYK,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,1,0,0,0.00,0.00
215,1642263,207,Reed Sheppard,1610612745,HOU,3,10,0,2,0.000,0,2,0.000,0,0,0.000,0,1,1,1,2,1,1,1,0,2,1.00,2.00
216,1629003,207,Shake Milton,1610612747,LAL,2,4,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,1,0,-1,0.00,0.00
217,1641783,207,Tristan da Silva,1610612753,ORL,2,5,0,1,0.000,0,1,0.000,0,0,0.000,0,4,4,1,0,0,2,0,0,2,0.50,0.00
218,1628427,207,Vlatko Čančar,1610612743,DEN,3,11,0,0,0.000,0,0,0.000,0,0,0.000,0,2,2,0,0,0,2,0,0,0,0.00,0.00

In [29]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
temp_df2 = pd.DataFrame({'Year': ['2024-25' for i in range(len(temp_df1))],
                         'Season_type': ['Playoffs' for i in range(len(temp_df1))]})

temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2024-25,Playoffs,1628983,1,Shai Gilgeous-Alexander,1610612760,OKC,23,851,233,504,0.462,32,113,0.283,190,217,0.876,23,100,123,150,38,20,60,65,688,661,2.50,0.63
1,2024-25,Playoffs,1628973,2,Jalen Brunson,1610612752,NYK,18,680,181,393,0.461,48,134,0.358,120,141,0.851,12,50,62,126,8,5,55,59,530,443,2.29,0.14
2,2024-25,Playoffs,1631114,3,Jalen Williams,1610612760,OKC,23,796,178,396,0.449,35,115,0.304,101,128,0.789,24,103,127,111,32,9,41,50,492,485,2.71,0.78
3,2024-25,Playoffs,1627783,4,Pascal Siakam,1610612754,IND,23,771,175,341,0.513,35,82,0.427,87,122,0.713,30,116,146,78,28,16,30,66,472,509,2.60,0.93
4,2024-25,Playoffs,1630169,5,Tyrese Haliburton,1610612754,IND,23,772,146,315,0.463,54,159,0.340,53,64,0.828,7,116,123,197,30,15,53,39,399,531,3.72,0.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,2024-25,Playoffs,200782,207,P.J. Tucker,1610612752,NYK,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,1,0,0,0.00,0.00
215,2024-25,Playoffs,1642263,207,Reed Sheppard,1610612745,HOU,3,10,0,2,0.000,0,2,0.000,0,0,0.000,0,1,1,1,2,1,1,1,0,2,1.00,2.00
216,2024-25,Playoffs,1629003,207,Shake Milton,1610612747,LAL,2,4,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,1,0,-1,0.00,0.00
217,2024-25,Playoffs,1641783,207,Tristan da Silva,1610612753,ORL,2,5,0,1,0.000,0,1,0.000,0,0,0.000,0,4,4,1,0,0,2,0,0,2,0.50,0.00
218,2024-25,Playoffs,1628427,207,Vlatko Čančar,1610612743,DEN,3,11,0,0,0.000,0,0,0.000,0,0,0.000,0,2,2,0,0,0,2,0,0,0,0.00,0.00

In [30]:
del temp_df3, temp_df1, temp_df2

In [31]:
df_cols = ['Year','Season_type'] + table_headers

In [32]:
headers = {
    'accept' : '*/*',
    'accept-encoding':'gzip, deflate, br, zstd',
    'accept-language':'en-US,en;q=0.9',
    'connection':'keep-alive',
    'host': 'stats.nba.com',
    'origin': 'https://www.nba.com',
    'referer':'https://www.nba.com/',
    'sec-ch-ua':'"Chromium";v="134", "Not:A-Brand";v="24", "Opera GX";v="119"',
    'sec-ch-ua-mobile':'?0',
    'sec-ch-ua-platform':'"Windows"',
    'sec-fetch-dest':'empty',
    'sec-fetch-mode':'cors',
    'sec-fetch-site': 'same-site',
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 OPR/119.0.0.0'
}

In [33]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = f'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season={y}&SeasonType={s}&StatCategory=PTS'
        r = requests.get(url=api_url, headers=headers).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
        temp_df2 = pd.DataFrame({'Year': [y for i in range(len(temp_df1))],
                                'Season_type': [s for i in range(len(temp_df1))]})

        temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
        df = pd.concat([df, temp_df3], axis=0)
        print(f'Finished scraping {y} {s}')

        '''
        lag = np.random.uniform(low=5, high=40)
        print(f'Waiting for {lag:.2f} seconds before next request...')
        time.sleep(lag)'''

print('Finished scraping all data! Total time taken:', (round((time.time() - begin_loop) / 60),2), 'minutes')
df.to_excel('nba_league_leaders_2015-2025.xlsx', index=False)

C:\Users\rishi\AppData\Local\Temp\ipykernel_33212\1151937099.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Finished scraping 2015-16 Regular%20Season
Finished scraping 2015-16 Playoffs
Finished scraping 2016-17 Regular%20Season
Finished scraping 2016-17 Playoffs
Finished scraping 2017-18 Regular%20Season
Finished scraping 2017-18 Playoffs
Finished scraping 2018-19 Regular%20Season
Finished scraping 2018-19 Playoffs
Finished scraping 2019-20 Regular%20Season
Finished scraping 2019-20 Playoffs
Finished scraping 2020-21 Regular%20Season
Finished scraping 2020-21 Playoffs
Finished scraping 2021-22 Regular%20Season
Finished scraping 2021-22 Playoffs
Finished scraping 2022-23 Regular%20Season
Finished scraping 2022-23 Playoffs
Finished scraping 2023-24 Regular%20Season
Finished scraping 2023-24 Playoffs
Finished scraping 2024-25 Regular%20Season
Finished scraping 2024-25 Playoffs
Finished scraping all data! Total time taken: (0, 2) minutes